## Assignment first

In [1]:
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
sb
plt
pd
np

In [4]:
df=pd.read_csv("/Users/apple/Desktop/internship_2nd_year/pandas/laptops+assignment1/laptopPrice.csv")

In [ ]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [ ]:
df.info(
    
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [5]:
df.describe()

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [ ]:
df.duplicated().sum()

21

In [6]:
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [7]:
df.duplicated().sum()

21

In [9]:
df.shape

(823, 19)

In [8]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [10]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [ ]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
df["processor_brand"].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [12]:
processor_dict = { 'Intel':0, 'AMD':1, 'M1':2 }
df['processor_brand']= df['processor_brand'].map(processor_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,0,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,0,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,0,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,1,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,1,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [13]:
df["processor_name"].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [14]:
processor_name_dict = {'Core i3':0, 'Core i5':1, 'Celeron Dual':2, 'Ryzen 5':3, 'Core i7':4,
       'Core i9':5, 'M1':6, 'Pentium Quad':7, 'Ryzen 3':8, 'Ryzen 7':9, 'Ryzen 9':10 }
df['processor_name']= df['processor_name'].map(processor_name_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,0,1,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,0,2,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,1,3,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [15]:
df.dropna(inplace=True)

In [16]:
df.dtypes

brand                object
processor_brand       int64
processor_name        int64
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [17]:
df.drop(['weight','msoffice','Number of Reviews'],axis = 1,inplace = True)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,Price,rating,Number of Ratings
0,ASUS,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,34649,2 stars,3
1,Lenovo,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,38999,3 stars,65
2,Lenovo,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,39999,3 stars,8
3,ASUS,0,1,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No warranty,No,69990,3 stars,0
4,ASUS,0,2,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No warranty,No,26990,3 stars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,135990,3 stars,0
819,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,144990,3 stars,0
820,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,149990,3 stars,0
821,ASUS,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,142990,3 stars,0
822,Lenovo,1,3,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No warranty,No,57490,4 stars,18

In [ ]:
df["brand"]

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 802, dtype: object

In [ ]:
df["os"]

0      Windows
1      Windows
2      Windows
3      Windows
4      Windows
        ...
818    Windows
819    Windows
820    Windows
821    Windows
822        DOS
Name: os, Length: 802, dtype: object

In [18]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [19]:
brand_dict = { 'ASUS':0, 'Lenovo':1, 'acer':2, 'Avita':3, 'HP':4, 'DELL':5, 'MSI':6, 'APPLE':7}
df['brand']= df['brand'].map(brand_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,Price,rating,Number of Ratings
0,0,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,34649,2 stars,3
1,1,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,38999,3 stars,65
2,1,0,0,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,39999,3 stars,8
3,0,0,1,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No warranty,No,69990,3 stars,0
4,0,0,2,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No warranty,No,26990,3 stars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,135990,3 stars,0
819,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,144990,3 stars,0
820,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,149990,3 stars,0
821,0,1,10,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,142990,3 stars,0
822,1,1,3,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No warranty,No,57490,4 stars,18

In [20]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [21]:
pr_gen = {'10th':10, 'Not Available':99, '11th':11, '7th':7, '8th':8, '9th':9, '4th':4,
       '12th':12 }

In [22]:
df['processor_gnrtn'] = df['processor_gnrtn'].map(pr_gen)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,Price,rating,Number of Ratings
0,0,0,0,10,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,34649,2 stars,3
1,1,0,0,10,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,38999,3 stars,65
2,1,0,0,10,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,39999,3 stars,8
3,0,0,1,10,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No warranty,No,69990,3 stars,0
4,0,0,2,99,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No warranty,No,26990,3 stars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,135990,3 stars,0
819,0,1,10,99,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,144990,3 stars,0
820,0,1,10,99,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,149990,3 stars,0
821,0,1,10,99,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,142990,3 stars,0
822,1,1,3,10,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No warranty,No,57490,4 stars,18

In [23]:
df['ram_gb'].unique()
df['ram_gb'].value_counts()

ram_gb
8 GB     418
4 GB     226
16 GB    177
32 GB      2
Name: count, dtype: int64

In [24]:
ram_dict = {'4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32 }
df['ram_gb'] = df['ram_gb'].map(ram_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,Price,rating,Number of Ratings
0,0,0,0,10,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,34649,2 stars,3
1,1,0,0,10,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,38999,3 stars,65
2,1,0,0,10,4,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,39999,3 stars,8
3,0,0,1,10,8,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,No warranty,No,69990,3 stars,0
4,0,0,2,99,4,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,No warranty,No,26990,3 stars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,135990,3 stars,0
819,0,1,10,99,4,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,144990,3 stars,0
820,0,1,10,99,4,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,149990,3 stars,0
821,0,1,10,99,4,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,142990,3 stars,0
822,1,1,3,10,8,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,No warranty,No,57490,4 stars,18

In [ ]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [25]:
df.drop(['ram_type'],axis = 1,inplace = True)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,os,os_bit,graphic_card_gb,warranty,Touchscreen,Price,rating,Number of Ratings
0,0,0,0,10,4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,34649,2 stars,3
1,1,0,0,10,4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,38999,3 stars,65
2,1,0,0,10,4,0 GB,1024 GB,Windows,64-bit,0 GB,No warranty,No,39999,3 stars,8
3,0,0,1,10,8,512 GB,0 GB,Windows,32-bit,2 GB,No warranty,No,69990,3 stars,0
4,0,0,2,99,4,0 GB,512 GB,Windows,64-bit,0 GB,No warranty,No,26990,3 stars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,135990,3 stars,0
819,0,1,10,99,4,1024 GB,0 GB,Windows,64-bit,0 GB,1 year,No,144990,3 stars,0
820,0,1,10,99,4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,149990,3 stars,0
821,0,1,10,99,4,1024 GB,0 GB,Windows,64-bit,4 GB,1 year,No,142990,3 stars,0
822,1,1,3,10,8,512 GB,0 GB,DOS,64-bit,0 GB,No warranty,No,57490,4 stars,18

In [26]:
df.drop(['os_bit','Number of Ratings'],axis = 1,inplace = True)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,os,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0 GB,1024 GB,Windows,0 GB,No warranty,No,34649,2 stars
1,1,0,0,10,4,0 GB,1024 GB,Windows,0 GB,No warranty,No,38999,3 stars
2,1,0,0,10,4,0 GB,1024 GB,Windows,0 GB,No warranty,No,39999,3 stars
3,0,0,1,10,8,512 GB,0 GB,Windows,2 GB,No warranty,No,69990,3 stars
4,0,0,2,99,4,0 GB,512 GB,Windows,0 GB,No warranty,No,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024 GB,0 GB,Windows,0 GB,1 year,No,135990,3 stars
819,0,1,10,99,4,1024 GB,0 GB,Windows,0 GB,1 year,No,144990,3 stars
820,0,1,10,99,4,1024 GB,0 GB,Windows,4 GB,1 year,No,149990,3 stars
821,0,1,10,99,4,1024 GB,0 GB,Windows,4 GB,1 year,No,142990,3 stars
822,1,1,3,10,8,512 GB,0 GB,DOS,0 GB,No warranty,No,57490,4 stars

In [38]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [39]:
touch_dict = { 'No':0, 'Yes':1}
df['Touchscreen'] = df['Touchscreen'].map(touch_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0,0,0,34649,2 stars
1,1,0,0,10,4,0,1024,0,0,0,38999,3 stars
2,1,0,0,10,4,0,1024,0,0,0,39999,3 stars
3,0,0,1,10,8,512,0,2,0,0,69990,3 stars
4,0,0,2,99,4,0,512,0,0,0,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0,1,0,135990,3 stars
819,0,1,10,99,4,1024,0,0,1,0,144990,3 stars
820,0,1,10,99,4,1024,0,4,1,0,149990,3 stars
821,0,1,10,99,4,1024,0,4,1,0,142990,3 stars
822,1,1,3,10,8,512,0,0,0,0,57490,4 stars

In [27]:
df['ssd'].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [28]:
ssd_dict = { '0 GB':0, '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':2048,
       '3072 GB':3072}
df['ssd'] = df['ssd'].map(ssd_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,os,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024 GB,Windows,0 GB,No warranty,No,34649,2 stars
1,1,0,0,10,4,0,1024 GB,Windows,0 GB,No warranty,No,38999,3 stars
2,1,0,0,10,4,0,1024 GB,Windows,0 GB,No warranty,No,39999,3 stars
3,0,0,1,10,8,512,0 GB,Windows,2 GB,No warranty,No,69990,3 stars
4,0,0,2,99,4,0,512 GB,Windows,0 GB,No warranty,No,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0 GB,Windows,0 GB,1 year,No,135990,3 stars
819,0,1,10,99,4,1024,0 GB,Windows,0 GB,1 year,No,144990,3 stars
820,0,1,10,99,4,1024,0 GB,Windows,4 GB,1 year,No,149990,3 stars
821,0,1,10,99,4,1024,0 GB,Windows,4 GB,1 year,No,142990,3 stars
822,1,1,3,10,8,512,0 GB,DOS,0 GB,No warranty,No,57490,4 stars

In [29]:
df.drop(['os'], axis=1, inplace=True, errors='ignore')
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024 GB,0 GB,No warranty,No,34649,2 stars
1,1,0,0,10,4,0,1024 GB,0 GB,No warranty,No,38999,3 stars
2,1,0,0,10,4,0,1024 GB,0 GB,No warranty,No,39999,3 stars
3,0,0,1,10,8,512,0 GB,2 GB,No warranty,No,69990,3 stars
4,0,0,2,99,4,0,512 GB,0 GB,No warranty,No,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0 GB,0 GB,1 year,No,135990,3 stars
819,0,1,10,99,4,1024,0 GB,0 GB,1 year,No,144990,3 stars
820,0,1,10,99,4,1024,0 GB,4 GB,1 year,No,149990,3 stars
821,0,1,10,99,4,1024,0 GB,4 GB,1 year,No,142990,3 stars
822,1,1,3,10,8,512,0 GB,0 GB,No warranty,No,57490,4 stars

In [31]:
hdd_dict = {'1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048 }
df['hdd'] = df['hdd'].map(hdd_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0 GB,No warranty,No,34649,2 stars
1,1,0,0,10,4,0,1024,0 GB,No warranty,No,38999,3 stars
2,1,0,0,10,4,0,1024,0 GB,No warranty,No,39999,3 stars
3,0,0,1,10,8,512,0,2 GB,No warranty,No,69990,3 stars
4,0,0,2,99,4,0,512,0 GB,No warranty,No,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0 GB,1 year,No,135990,3 stars
819,0,1,10,99,4,1024,0,0 GB,1 year,No,144990,3 stars
820,0,1,10,99,4,1024,0,4 GB,1 year,No,149990,3 stars
821,0,1,10,99,4,1024,0,4 GB,1 year,No,142990,3 stars
822,1,1,3,10,8,512,0,0 GB,No warranty,No,57490,4 stars

In [32]:
df['hdd'].unique()

array([1024,    0,  512, 2048])

In [33]:
df['warranty'].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [34]:
warr_dict={'No warranty':0, '1 year':1, '2 years':2, '3 years':3 }

In [35]:
df['warranty'] = df['warranty'].map(warr_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0 GB,0,No,34649,2 stars
1,1,0,0,10,4,0,1024,0 GB,0,No,38999,3 stars
2,1,0,0,10,4,0,1024,0 GB,0,No,39999,3 stars
3,0,0,1,10,8,512,0,2 GB,0,No,69990,3 stars
4,0,0,2,99,4,0,512,0 GB,0,No,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0 GB,1,No,135990,3 stars
819,0,1,10,99,4,1024,0,0 GB,1,No,144990,3 stars
820,0,1,10,99,4,1024,0,4 GB,1,No,149990,3 stars
821,0,1,10,99,4,1024,0,4 GB,1,No,142990,3 stars
822,1,1,3,10,8,512,0,0 GB,0,No,57490,4 stars

In [36]:
df['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [37]:
graphics_dict = {'0 GB': 0, '2 GB': 2, '4 GB': 4, '6 GB': 6, '8 GB': 8}
df['graphic_card_gb'] = df['graphic_card_gb'].map(graphics_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0,0,No,34649,2 stars
1,1,0,0,10,4,0,1024,0,0,No,38999,3 stars
2,1,0,0,10,4,0,1024,0,0,No,39999,3 stars
3,0,0,1,10,8,512,0,2,0,No,69990,3 stars
4,0,0,2,99,4,0,512,0,0,No,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0,1,No,135990,3 stars
819,0,1,10,99,4,1024,0,0,1,No,144990,3 stars
820,0,1,10,99,4,1024,0,4,1,No,149990,3 stars
821,0,1,10,99,4,1024,0,4,1,No,142990,3 stars
822,1,1,3,10,8,512,0,0,0,No,57490,4 stars

In [40]:
cat_col = df.select_dtypes(include='object')
num_col = df.select_dtypes(exclude='object')

In [43]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0,0,0,34649,2 stars
1,1,0,0,10,4,0,1024,0,0,0,38999,3 stars
2,1,0,0,10,4,0,1024,0,0,0,39999,3 stars
3,0,0,1,10,8,512,0,2,0,0,69990,3 stars
4,0,0,2,99,4,0,512,0,0,0,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0,1,0,135990,3 stars
819,0,1,10,99,4,1024,0,0,1,0,144990,3 stars
820,0,1,10,99,4,1024,0,4,1,0,149990,3 stars
821,0,1,10,99,4,1024,0,4,1,0,142990,3 stars
822,1,1,3,10,8,512,0,0,0,0,57490,4 stars

In [ ]:
df = df.drop_duplicates()
print("After removing duplicates:", df.shape)

After removing duplicates: (782, 12)

In [46]:
print("\nMissing values per column:")
print(df.isnull().sum())

if 'Rating' in df.columns:
    df['Rating'] = df['Rating'].fillna(df['Rating'].median())

df = df.dropna()
print("\nAfter handling missing values:", df.shape)

Missing values per column:
brand              0
processor_brand    0
processor_name     0
processor_gnrtn    0
ram_gb             0
ssd                0
hdd                0
graphic_card_gb    0
warranty           0
Touchscreen        0
Price              0
rating             0
dtype: int64

After handling missing values: (782, 12)

In [48]:
for col in df.columns:
    if df[col].nunique() == 1:
        df.drop(col, axis=1, inplace=True)
        print(f"Dropped column with single value: {col}")

unwanted = ['Review Count', 'Rating Count']  # example: often similar / duplicate
df.drop(columns=[col for col in unwanted if col in df.columns], inplace=True)

In [49]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

print("\nCategorical Columns:", categorical_cols)
print("Numerical Columns:", numerical_cols)

Categorical Columns: ['rating']
Numerical Columns: ['brand', 'processor_brand', 'processor_name', 'processor_gnrtn', 'ram_gb', 'ssd', 'hdd', 'graphic_card_gb', 'warranty', 'Touchscreen', 'Price']

In [50]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0,0,0,34649,2 stars
1,1,0,0,10,4,0,1024,0,0,0,38999,3 stars
2,1,0,0,10,4,0,1024,0,0,0,39999,3 stars
3,0,0,1,10,8,512,0,2,0,0,69990,3 stars
4,0,0,2,99,4,0,512,0,0,0,26990,3 stars
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0,1,0,135990,3 stars
819,0,1,10,99,4,1024,0,0,1,0,144990,3 stars
820,0,1,10,99,4,1024,0,4,1,0,149990,3 stars
821,0,1,10,99,4,1024,0,4,1,0,142990,3 stars
822,1,1,3,10,8,512,0,0,0,0,57490,4 stars

In [54]:
df['rating'].unique()

array(['2 stars', '3 stars', '4 stars', '5 stars', '1 star'], dtype=object)

In [56]:
rating_dict = {'2 stars':2, '3 stars':3, '4 stars':4, '5 stars':5, '1 star':1}
df['rating'] = df['rating'].map(rating_dict)
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price,rating
0,0,0,0,10,4,0,1024,0,0,0,34649,2
1,1,0,0,10,4,0,1024,0,0,0,38999,3
2,1,0,0,10,4,0,1024,0,0,0,39999,3
3,0,0,1,10,8,512,0,2,0,0,69990,3
4,0,0,2,99,4,0,512,0,0,0,26990,3
...,...,...,...,...,...,...,...,...,...,...,...,...
818,0,1,10,99,4,1024,0,0,1,0,135990,3
819,0,1,10,99,4,1024,0,0,1,0,144990,3
820,0,1,10,99,4,1024,0,4,1,0,149990,3
821,0,1,10,99,4,1024,0,4,1,0,142990,3
822,1,1,3,10,8,512,0,0,0,0,57490,4

In [57]:
df.to_csv('laptopassignment.csv', encoding='utf-8', index=False)